# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4cb1de3a152c381cf010fd383f99858b8288690496f7faeaac643f67ee2883e5bfbcf3fcb2e195801a10b88cd951239f97314c9cbd16195de4f9df554a3e2a08

test:
  secret_key_base: 2cd6a203a4194d318b7b5f0f6cf141bb5c7f535c395b7a99ebbcdba151e8a1eea262f45cbbf1a995d64465f6778c668f46602454d6bdaa1d8eb09dd8fef5d6fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
